uavs_info:
  num_uavs: 3
  uav_1:
    name: 'iris_1'
    r: 255
    g: 25
    b: 25
    setpoint:
      x: 0
      y: 0
      z: 2
      vx: 0
      vy: 0
      vz: 0
      yaw: 0
  uav_2:
    name: 'iris_2'
    r: 0
    g: 227
    b: 9
    setpoint:
      x: 1.5
      y: 1
      z: 2
      vx: 0
      vy: 0
      vz: 0
      yaw: -2.5
  uav_3:
    name: 'iris_3'
    r: 20
    g: 25
    b: 255
    setpoint:
      x: 1.5
      y: 0
      z: 2
      vx: 0
      vy: 0
      vz: 0
      yaw: 1.5708